version: '3.5'

services:
  exchange-currency:
    container_name: exchange-currency
    build:
      context: ../../
      dockerfile: ./deploy/web/Dockerfile
    command: npm run dev
    restart: on-failure
    volumes:
      - node_modules:/app/node_modules
      - ../../:/app
    logging:
      driver: "json-file"
      options:
        max-size: "999k"
    ports:
      - 4000:4000
volumes:
  node_modules:
